const coods = {
  name: "image-map",
  areas: [
    {
      target: "",
      name: "ล้อหน้าขวา",
      position: "หน้า",
      href: "",
      coords: [20, 59, 126, 97],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหน้าซ้าย",
      position: "หน้า",
      href: "",
      coords: [21, 174, 124, 212],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าขวา",
      position: "หน้า",
      href: "",
      coords: [127, 61, 230, 98],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าขวา2",
      position: "หน้า",
      href: "",
      coords: [126, 99, 230, 134],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าซ้าย",
      position: "หน้า",
      href: "",
      coords: [128, 137, 230, 174],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าซ้าย2",
      position: "หน้า",
      href: "",
      coords: [126, 173, 229, 211],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังขวา",
      position: "หน้า",
      href: "",
      coords: [230, 60, 334, 97],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังขวา2",
      position: "หน้า",
      href: "",
      coords: [230, 134, 336, 98],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังซ้าย",
      position: "หน้า",
      href: "",
      coords: [231, 173, 336, 137],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังซ้าย2",
      position: "หน้า",
      href: "",
      coords: [231, 210, 336, 174],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหน้าขวาหลัง",
      position: "หลัง",
      href: "",
      coords: [360, 60, 466, 95],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหน้าขวาหลัง2",
      position: "หลัง",
      href: "",
      coords: [361, 134, 464, 98],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหน้าซ้ายหลัง",
      position: "หลัง",
      href: "",
      coords: [361, 174, 464, 135],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหน้าซ้ายหลัง2",
      position: "หลัง",
      href: "",
      coords: [362, 211, 466, 173],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าขวา",
      position: "หลัง",
      href: "",
      coords: [466, 59, 573, 97],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าขวา2",
      position: "หลัง",
      href: "",
      coords: [466, 135, 571, 98, 467, 173],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าซ้าย",
      position: "หลัง",
      href: "",
      coords: [467, 172, 571, 135],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังหน้าซ้าย2",
      position: "หลัง",
      href: "",
      coords: [467, 211, 571, 174],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังขวา",
      position: "หลัง",
      href: "",
      coords: [573, 96, 678, 60],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังขวา2",
      position: "หลัง",
      href: "",
      coords: [573, 135, 677, 97],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังซ้าย",
      position: "หลัง",
      href: "",
      coords: [573, 172, 677, 137],
      shape: "rect",
    },
    {
      target: "",
      name: "ล้อหลังซ้าย2",
      position: "หลัง",
      href: "",
      coords: [573, 210, 678, 174],
      shape: "rect",
    },
  ],
}

export default coods
